apiVersion: apps/v1
kind: Deployment
metadata:
  name: javademo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: javademo
  template:
    metadata:
      labels:
        app: javademo
    spec:
      containers:
      - image: 20.98.70.140/alpha/spring-demo:latest
        name: javademo
        ports:
        - containerPort: 8080
      imagesPullSecrets:
      - name: regcred

